### ISSUE TITLE
Create the diagram representing tiles in columns.

### ISSUE THREAD

**Issue by joanma747** [opengeospatial/2D-Tile-Matrix-Set#27]
To introduce more dimensions we can think on 3 levels:
1.- Columns on top of a 2dTles  (CDB uses this)
2.- Columns divided in "blocks" on topo fo 2d tiles that will be described by a 3Dtilematrix
3.- Columns that changes the number of divisions in the same way as the 2D in each scale change
(and consider this also more dimensions for time and ...)

Jerome's version.
1. Extend in other dimension; Use TMS as is, reduce content with level 
2. Add slices in other dimension (but overviews still based only on other dimensions)
3. Change the number of slices in other dimension as well at lower levels (turning into octree or hyperoctree) hexadecitree

We could to add a comment on the relation with 3DTiles and what they do with their "boxes"

**Comment by joanma747** [comment]
![image](https://user-images.githubusercontent.com/5230444/117323098-e37ad880-ae8e-11eb-93dc-87b1335dddd8.png)

**Comment by joanma747** [comment]
Let's generate a better diagram for the 3 cases:

This diagrams need an explanation because the xy dimension varies in size (scale) but the z coordinate does not.

Case 1: 1.- Columns on top of a 2dTles (CDB uses this) (Extend in other dimension; Use TMS as is, reduce content with level)
![image](https://user-images.githubusercontent.com/5230444/118106181-a017f100-b3dd-11eb-8ec9-e9cc331f2412.png)

Case 2: Add slices in other dimension (but overviews still based only on other dimensions)
![image](https://user-images.githubusercontent.com/5230444/118106318-c5a4fa80-b3dd-11eb-9d91-b0b44fbb9f64.png)

Case 3: Change the number of slices in other dimension as well at lower levels (turning into octree or hyperoctree) hexadecitree
![image](https://user-images.githubusercontent.com/5230444/118106348-cd649f00-b3dd-11eb-913f-5dd6f87e1199.png)


Can I suggest to use tileWidth, tileHeight tileElevation tileTime... tileExtraDim1... for the names of an nD model? In the document, we could give some clues on how to extend the model and encodings to add extra dimensions without actually doing it. A possibility is to have a an annex to discuss a nD extension.

**Comment by jerstlouis** [comment]
@joanma747 Awesome diagrams!!! Thank you!

Actually I think we may not need to specify `tile*` at all for the extra dimensions, since those are strictly concerned with the resolution of the data from a 2D map perspective, not the tiling / division. Actually, I was discussing with Carl about that yesterday (in the context of drafting the CDB X specifications and referencing TMS), and we could potentially split the concepts of tiling and resolution/scale/Level of Detail  in TMS: e.g. you could instantiate the GNOSISGlobalGrid with 256 tileMatrixWidth x 256 tileMatrixHeight, but the exact same tiling could be used with 512 tileMatrixWidth x 512 tileMatrixHeight.

I think there are better ways to define the vertical or temporal (or other kind of dimension) resolution than specifying a number of pixels, in fact it would make very little sense for temporal.

What we should define though is the lower/upper bound for the whole range, and into how many blocks we're dividing (i.e. the `matrix*` values). And maybe we could use a map/dictionary if can be associated strictly by name at the TMS definition level, or otherwise use an ordered array, e.g.:

```json
   {
         "identifier" : "0",
         "scaleDenominator" : 139770566.0071794390678,
         "matrixWidth" : 4,
         "matrixHeight" : 2,
         "tileWidth" : 256,
         "tileHeight" : 256,
         "pointOfOrigin" : [
            90,
            -180
         ],
         "matrixExtraDimensions" :
         {
            "elevation" : {
               "min" : -12000, "max" : 10000,
               "uom" : "http://www.opengis.net/def/uom/SI/metre",
               "divisions" : 10,
               "resolution" : 44
            },
            "time" : {
               "min" : "2021-01-01", "max" : "2021-12-31",
               "uom" :  "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian",
               "divisions" : 12,
               "temporalDivision" : "month",
               "tenmporalResolution" : "day"
            },
         }
      },
```

So with this idea for _matrixExtraDimensions_, for each dimension:
- The map key is the name
- `min` is the minimum value 
- `max` is the maximum value
- `uom` is the unit of measure used for defining `min`, `max` and `resolution`
- `divisions` is in how many blocks (_trims_ in Coverages term) the space between `min` & `max` is divided at this particular tile matrix
- `resolution` is the resolution of the data in that dimension. For a coverage, this would be separate slices at that resolution interval, where the number of slices is equal to (`max` - `min`) / `divisions` / `resolution`, (+1 for _points_ rather than _area_ coverage). For 3D models, point clouds, vector features, the resolution would represent the average accuracy level at which you will find distinct coordinates.

For temporal, I suggest `temporalDivision` and `temporalResolution` to allow dividing by month or years, which have unequal number of days (even even days have unequal number of seconds with leap seconds), and similarly specify the resolution using these not-so-equally-spread units.

I believe that is all that is required fully supports case 2 & 3, and full nD coverage, point clouds 3D models (space-centric, i.e. irrespective of content) tiles.
Case 1 is already supported by the currenst schema.

I think we should also allow implementers to either:
1. Define a a _TileMatrixSet_ already built-in with this nD capability, or
2. Define these extra dimensions as part of a _TileSet_ using a 2D-only _TileMatrixSet_, by defining this `matrixExtraDimensions` for each tile matrix

Then in the _Tiles API_, we will only need to establish how those nD dimensions map to the different conformance classes to support identifying a specific nD tile. I believe that would be quite straightforward based on how they are organized.

**Comment by jerstlouis** [comment]
Maybe we should rename `resolution` and `temporalResolution` to `cellSize` and `temporalCellSize`.

We could also consider merging `cellSize` and `temporalCellSize`, and `divisions` and `temporalDivision` (specifying "month" for `divisions`, and the number of divisions would be based on how many months are covered by the range).

**Comment by joanma747** [comment]
I agree with having a generic structure for the extra dimensions.

In order to make the notation more symmetric witht he 2D dimensions, I propose:

```
{
         "identifier" : "0",
         "scaleDenominator" : 139770566.0071794390678,
         "cellSize": 0.3515625,
         "matrixWidth" : 4,
         "matrixHeight" : 2,
         "tileWidth" : 256,
         "tileHeight" : 256,
         "pointOfOrigin" : [
            90,
            -180
         ],
         "extraDimensions" :
         {
            "elevation" : {
               "origin" : -12000,
               //"end" : 10000, optional
               "uom" : "http://www.opengis.net/def/uom/SI/metre",
               "matrixAcross" : 22,
               "tileAcross" : 1000
            },
            "time" : {
               "origin" : "2021-01-01", 
               "uom" :  "http://www.opengis.net/def/uom/ISO-8601/0/Gregorian",
               "matrixAcross" : "monthsInAYear*2",
               "tileAcross" : "daysInAMonth"
            }
         }
   }
```

The word "Across" comes from the TIFF tiles and it is a bit more dimension agnostic than "width" or "height".

**Comment by jerstlouis** [comment]
@joanma747 

I had originally thought of using something like `tileAcross` and had called it `slices`, from the Coverages terminology. The reason I went away from that, is that just like with vector data we get a lot of pushback about these 256 pixels being meaningless, with 3D point clouds or models, there is no fixed number of elements across -- the points or mesh vertices are not equally spaced. That's why I suggested `resolution` instead.

For temporal, years, months, weeks, days, hours, minutes can all correspond to a different number of seconds.
_daysInAMonth_ by itself is confusing since not all months have the same number of days.
The _matrixAcross_ in particular should be a clear value (which works in your example because _monthsInAYear_ is one thing that is fixed).
I also thought it was nice to be able to easily see and easier to specify what is the temporal resolution at a particular tile matrix, rather than the number of elements which is always wobbly.

**Comment by joanma747** [comment]
The diagrams works for projected spaces but in an sphere, the columns are not columns are wider at the top. [Carl's comment]

**Comment by jerstlouis** [comment]
I volunteer to create an annex for this, and remove the 2D suffixes throughout the class names.

**Comment by jerstlouis** [comment]
We now have _Annex K: Extending TileMatrixSets for additional dimensions (Informative)_!

**Comment by joanma747** [comment]
The annex is considered done.
