### ISSUE TITLE
Section 5.3.3

### ISSUE THREAD

**Issue by ayoumans** [opengeospatial/2D-Tile-Matrix-Set#39]
CRSum...is this an error?  Where does this come from?

**Comment by jerstlouis** [comment]
@ayoumans it is a mistake.

@joanma747 At least this sentence needs to be rewritten in my opinion as I cannot make sense of it grammatically:

> Specifically, Ordered list of names of the dimensions defined in the CRSum rectangular bounding region surrounding a geometry whose set of points span the value discontinuity in an angular coordinate axis.

The CRSum mistake was introduced by https://github.com/opengeospatial/2D-Tile-Matrix-Set/commit/b0b6cbeea61291c379f5e4a918368287979c396b#diff-0add2601d8308c9591e3a5cf929e41a16c4e9c1d7916e8888e7eea9aa49c8815L124

The sentence starts with _specifically_, but I have no idea what this _specifically_ refers to?
It talks about _Ordered list of names_, but that seems unrelated to the rest of the sentence.

This paragraph and the next seems to be talking about intricacies with angular units and some kind of projections near the poles when specifying the bounding box of the TileMatrixSet, but I am not clear on why that bounding box would not be a minimum rectangular bounding region?

Perhaps with version 2 which has a separate bounding box for the TileSet this is no longer relevant, since the bounding box here is not about the data, but about the definitions of the tile matrix set itself?

**Comment by joanma747** [comment]
Thanks for spotting the mistake and when the mistake was produced.
It is clear to me that this was some wrong editorial process. 
I have rolled the sentence back.
