### ISSUE TITLE
Consider using resolution instead of scaleDenominator

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/2D-Tile-Matrix-Set#4]
I know that there is a legacy of `scaleDenominator` in OGC specs, but I'm wondering if there has been any discussion about starting fresh on this spec.

The concept of "scale" doesn't apply well to digital maps.  Broadly speaking, a rendering client may not be able to determine the physical pixel size of a display device.  Newcomers to the Tiles spec may scratch their heads for a while trying to figure out how the server is supposed to know the pixel size of the display if the client can't even reliably determine it.  After digging for a while through other OGC specs, they may discover the magic 0.28 mm "standardized rendering pixel size" and copy this into their code.

Since 0.28 mm will rarely (never? - try to find a 90.7 PX / inch device here http://screensiz.es/) be the physical size of a pixel, the `scaleDenominator` has no real meaning and only serves as a source of confusion for those that assume it does.

Instead of using the confusing `scaleDenominator` and requiring that implementors discover the magic 0.28 mm number, tile levels could be described in terms of `resolution` (number of map units per pixel).  It is the resolution that a client needs to know in order to render tiles on a map.

**Comment by joanma747** [comment]
Annex D of 2D-TMS exposes 2 columns one for pixel size (so called "resolution" next to the scaleDenominator. 
Historically we use scaleDenominator and 0.28 because WMS 1.1-1.3 and SLD uses it. We wanted to be consistent with it.

Pixel size is a "true" for all devices that are directly using "one pixel in the viewport"="one pixel in the tile". This is "one way of doing this" but not necessarily the only one.

In the WMS meeting 2020/08/06 we make a motion:
"We will add "Pixel Size" in projected coordinates (as defined in 2D TMS standard) to the TileMatrix description (UML, XML and JSON encodings). Both Pixel Size and ScaleDenominator will be required
Moved by Jeff Harrison
Seconded by Jerome St.Lou
Discussion: Name? Resolution, Projected Pixel Size,  
NOTUC

We will close the issue when this is applied to 2D TMS.

**Comment by joanma747** [comment]
We recognize that there is a "true resolution" of the data and we expect the API Common will address or provide that in the description of the collection (included in part 2)

**Comment by tschaub** [comment]
Good to hear that there is support for requiring `resolution` (or whatever it will be named).  This makes it possible for clients to render tiles without unnecessary dependencies.

Making `scaleDenominator` required adds additional dependencies for clients.  Theses are dependencies that are not required to render tiles.  Can you describe the reasoning for requiring these?

**Comment by tschaub** [comment]
Good to hear that `resolution` will be required (with this or some other name).  Thanks for considering the minimal client / no dependency case.

**Comment by cholmes** [comment]
Any movement on this? Getting it in the spec? This is a really great decision, would be good to get it published, so that OpenLayers can get add this as a new tile source, and people can start to build simpler implementations.

**Comment by joanma747** [comment]
Action for the editor: **add** "resolution"/"pixelsize" to tilematrix as well as in TileMatrixSetLimits. Both are mandatori.

**Comment by joanma747** [comment]
I took some time but this is finally done everywhere in the document schemas and examples.

**Comment by tschaub** [comment]
Thanks for the update, @joanma747.

**Comment by tschaub** [comment]
For anybody else who may be reading, are there people that are implementing the changes to this spec?  I'm wondering if changes to the spec like this (adding `cellSize` or the change to `pointOfOrigin` and `cornerOfOrigin`) are being implemented by anybody as they are being specified.
